import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/app/_components/Navbar";
import Footer from "@/app/_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-dark text-white`}>
        <Navbar />
        <main className="max-w-[1560px] m-auto p-10 min-h-[90vh]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
